[build]
  command = "npm run build"
  publish = "dist/client"
  functions = "dist/server"

[template.environment]
  NODE_ENV = "Node Environment"
  CLOUDINARY_CLOUD_NAME = "Cloudinary Cloud Name"
  GA_TRACKING_ID = "Google Analytics Tracking ID"
