[build]
  command = "npm run build"
  publish = "dist/client"
  functions = "dist/server"

[template.environment]
  CLOUDINARY_URL = "Cloudinary URL"
  GA_TRACKING_ID = "Google Analytics Tracking ID"
